name: test pr push

on:
  pull_request:
    branches: [ "master"]

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3 # Checks out the repository code
#     - name: Display PR Number
#       run: echo "The pull request number is: ${{ github.event.pull_request.number }}"
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Display PR Number
      run: |
        echo "The pull request number is: ${{ github.event.pull_request.number }}"
        
    - name: Chekout code 
      uses: actions/checkout@v3 
      with:
        fetch-depth: 0
    
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: check for changes in the python file
      run: | 
          # diff_docker_file=$(git diff --name-only origin/master...HEAD | grep -E '^.*py$' || echo "")
          # diff_requirements_txt=$(git diff --name-only origin/master...HEAD | grep -E '^.*Dockerfile$' || echo "")
          diff_docker_file=$(git diff --name-only origin/master...HEAD | grep -E '^.*Dockerfile$' || echo "")
          diff_requirements_txt=$(git diff --name-only origin/master...HEAD | grep -E '^.*requirements.txt$' || echo "")
          echo $(pwd)
          if [ -z "$diff_docker_file" ] && [ -z "$diff_requirements_txt" ]; then
            echo "No change made to the Dockerfile and the requirements.txt file."
          
          elif [ -z "$diff_docker_file" ] && [ -n "$diff_requirements_txt" ]; then
            echo "Changes made to the requirements.txt file:"
            for file in $diff_requirements_txt; do 
              echo "inside the file loop"
              echo $file
              IFS='/ ' read -r -a array <<< $file
              echo "${array[0]}"
              folder_name=$(echo "${array[0]}")
              full_path=$(echo "$folder_name""/Dockerfile")
              docker_repository_name="idowuilekura/dockgispy"
              tag_name=${folder_name#dockgispy}
              image_repository_path=$(echo "$docker_repository_name"":""$tag_name")
              # image_repository_path=$(echo "$docker_repository_name"":""$folder_name")
              echo "about to build the docker image"
              cd $folder_name
              echo "done changing the directory"
              docker build -t $image_repository_path . 
              echo "done building the docker image with name $image_repository_path"
              cd ..
              docker rmi -qf $(docker image ls -aq)
              echo "done removing all docker images on the repo"
              done

          elif [ -n "$diff_docker_file" ] && [ -z "$diff_requirements_txt" ]; then
            echo "Changes made to the dockerfile:"
            for file in $diff_docker_file; do 
              echo "inside the file loop"
              echo $file
              IFS='/ ' read -r -a array <<< $file
              echo "${array[0]}"
              folder_name=$(echo "${array[0]}")
              full_path=$(echo "$folder_name""/Dockerfile")
              docker_repository_name="idowuilekura/dockgispy"
              tag_name=${folder_name#dockgispy}
              image_repository_path=$(echo "$docker_repository_name"":""$tag_name")
              echo "about to build the docker image"
              cd $folder_name
              echo "done changing the directory"
              docker build -t $image_repository_path . 
              echo "done building the docker image with name $image_repository_path"
              cd ..
              docker rmi -qf $(docker image ls -aq)
              echo "done removing all docker images on the repo"
              done 


          else
            
            echo "ignoring things"
              
          fi
